config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'products#index'
  resources :signup do
    collection do
      get 'registration'
      get 'phone'
      get 'address'
      get 'pay_way'
      get 'complete'
    end
  end

  resources :purchase,  only: [:show] do
    member do
      patch 'pay'
    end
    collection do
      get 'complete'
    end
  end

  resources :mypage do
    member do
      get 'exhibiting'
      get 'sold'
      get 'purchased'
      get 'profile'
      get 'card'
      get 'identification'
      get 'logout'
    end
  end

  resources :users, only: [:update]

  resources :products do
    member do
      patch 'release'
      patch 'suspension'
    end
    collection do
      get 'category_child', defaults: { format: 'json' }
      get 'category_grandchild', defaults: { format: 'json' }
      get 'size', defaults: { format: 'json' }
      get 'brand', defaults: { format: 'json' }
      get 'delivery_way'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      get 'delete'
    end
  end

  resources :purchase do
    collection do
      get 'purchase_confirmation'
    end
    member do
      get 'pay'
    end
  end

  resources :category do
    collection do
      get 'new', defaults: { format: 'json' }
    end
  end
  
  resources :searches, only: [:index] do
    collection do
      get 'detail_search'
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  include RedirectToTop
  before_action :redirect_to_top, except: :complete
  before_action :apply_gon
  before_action :validates_registration, only: :phone
  before_action :validates_phone, only: :address  
  before_action :validates_address, only: :pay_way

  def registration # 会員情報入力
    @user = User.new
  end

  def phone # 電話番号入力
    @user = User.new
  end

  def address # 住所入力
    @user = User.new
  end

  def pay_way # 支払い方法入力
    @user = User.new
  end
  
  def complete # 登録完了
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  def create # ユーザーの会員情報登録→SNS登録→カード情報登録
    @user = User.new(
    name: session[:name],
    email: session[:email],
    password: session[:password],
    password_confirmation: session[:password_confirmation],
    phone: session[:phone],
    lastname: session[:lastname],
    firstname: session[:firstname],
    lastname_kana: session[:lastname_kana],
    firstname_kana: session[:firstname_kana],
    birth_year: session[:birth_year],
    birth_month: session[:birth_month],
    birth_day: session[:birth_day]
    )
    @user.build_address(session[:address])
    @user.sns_credentials.build(provider: session[:provider], uid: session[:uid]) if session[:provider] && session[:uid]
    if @user.save
      session[:id] = @user.id
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      if params['payjp-token'].blank?
        redirect_to pay_way_signup_index_path
      else
        customer = Payjp::Customer.create(
        card: params['payjp-token'],
        ) 
        @card = Card.new(user_id: session[:id], customer_id: customer.id, card_id: customer.default_card)
        if @card.save
          redirect_to complete_signup_index_path
        else
          render '/signup/payway'
        end
      end
    else
      render '/signup/registration'
    end
  end


  private
  
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :avatar,
      :introduction,
      :lastname,
      :firstname,
      :lastname_kana,
      :firstname_kana,
      :birth_year,
      :birth_month,
      :birth_day,
      :phone,
      address_attributes: [
        :id,
        :postal_code,
        :prefecture_id,
        :city,
        :street,
        :building_name,
        :phone_optional
      ]
    )
  end
  
  def validates_registration # 会員情報のバリデーションチェック
    session[:name] = user_params[:name]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:lastname] = user_params[:lastname]
    session[:firstname] = user_params[:firstname]
    session[:lastname_kana] = user_params[:lastname_kana]
    session[:firstname_kana] = user_params[:firstname_kana]
    session[:birth_year] = user_params[:birth_year]
    session[:birth_month] = user_params[:birth_month]
    session[:birth_day] = user_params[:birth_day]
    @user = User.new(
      name: session[:name],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      phone: "0123456789",
      lastname: session[:lastname],
      firstname: session[:firstname],
      lastname_kana: session[:lastname_kana],
      firstname_kana: session[:firstname_kana],
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      address_attributes: {
        postal_code:  "123-4567",
        prefecture_id:   "1",
        city:           "AAA",
        street:         "BBB",
        phone_optional:  "0123456789"
      }
    )
    render 'signup/registration' unless @user.valid?
  end

  def validates_phone # 電話番号のバリデーションチェック
    session[:phone] = user_params[:phone]
    @user = User.new(
      name: session[:name],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      phone: session[:phone],
      lastname: session[:lastname],
      firstname: session[:firstname],
      lastname_kana: session[:lastname_kana],
      firstname_kana: session[:firstname_kana],
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      address_attributes: {
        postal_code:  "123-4567",
        prefecture_id:   "1",
        city:           "AAA",
        street:         "BBB",
        phone_optional:  "0987654321"
      } 
    )
    render 'signup/phone' unless @user.valid?
  end

  def validates_address # 住所のバリデーションチェック
    session[:lastname] = user_params[:lastname]
    session[:firstname] = user_params[:firstname]
    session[:lastname_kana] = user_params[:lastname_kana]
    session[:firstname_kana] = user_params[:firstname_kana]
    session[:address] = user_params[:address_attributes]
    @user = User.new(
      name: session[:name],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      phone: session[:phone],
      lastname: session[:lastname],
      firstname: session[:firstname],
      lastname_kana: session[:lastname_kana],
      firstname_kana: session[:firstname_kana],
      birth_year: session[:birth_year],
      birth_month: session[:birth_month],
      birth_day: session[:birth_day],
      address_attributes: session[:address]
    )
    render 'signup/address' unless @user.valid?
  end

  def apply_gon
    gon.payjp_key = ENV["PAYJP_KEY"]
  end
end

app/views/signup/address.html.haml
.address
  %header.address__header
    %h1.address__header__left
      = link_to "/" , class: "address__header__left__logo" do
        = image_tag "fmarket_logo_red.svg", class: "address__header__left__logo__img"
    %nav.address__header__progress-bar
      %ol.address__header__progress-bar__clearfix
        %li.address__header__progress-bar__text
          会員情報
          .address__header__progress-bar__status.active
        %li.address__header__progress-bar__text
          電話番号認証
          .address__header__progress-bar__status.active
        %li.address__header__progress-bar__text.active
          お届け先住所入力
          .address__header__progress-bar__status.active.last
        %li.address__header__progress-bar__text
          支払い方法
          .address__header__progress-bar__status
        %li.address__header__progress-bar__text
          完了
          .address__header__progress-bar__status
  %main.address__main
    %section.address__main__container
      %h2.address__main__container__head  住所入力
      = form_for(@user, url: pay_way_signup_index_path, method: :get, html: {class: "address__main__form", id: "signup-form"}) do |f|
        %div.address__main__form__content
          = render partial: 'layouts/error-messages', locals: { user: @user, column: "address.phone_optional"}
          %div.address__main__form__content__group
            = f.label :name, "お名前", class: "address__main__form__content__group__label" 
            %span.address__main__form__content__group__require 必須
            = f.text_field :lastname, class: "address__main__form__content__group__input", placeholder:"例）山田", id: "lastname"
            = f.text_field :firstname, class: "address__main__form__content__group__input", placeholder:"例）彩", id: "firstname"
            #name_error
          %div.address__main__form__content__group
            = f.label :name_kana, "お名前カナ", class: "address__main__form__content__group__label" 
            %span.address__main__form__content__group__require 必須
            = f.text_field :lastname_kana, class: "address__main__form__content__group__input", placeholder:"例）ヤマダ", id: "lastname_kana"
            = f.text_field :firstname_kana, class: "address__main__form__content__group__input", placeholder:"例）アヤ", id: "firstname_kana"
            #name_kana_error
            = f.fields_for :address, @user.build_address do |address_form|
              %div.address__main__form__content__group
                = f.label :postal_code, "郵便番号", class: "address__main__form__content__group__label" 
                %span.address__main__form__content__group__require   必須
                = address_form.text_field :postal_code, class: "address__main__form__content__group__input", placeholder:"例）123-4567", id: "postal_code"
              %div.address__main__form__content__group
                = f.label :prefecture, "都道府県", class: "address__main__form__content__group__label"
                %span.address__main__form__content__group__require   必須
                .address__main__form__content__group__prefecture__select
                  %i.fas.fa-chevron-down.fa-lg.address__main__form__content__group__prefecture__select__icon
                  = address_form.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--", class: "address__main__form__content__group__prefecture__select__pulldown"
                  #prefecture_id_error
              %div.address__main__form__content__group
                = f.label :city, "市区町村", class: "address__main__form__content__group__label" 
                %span.address__main__form__content__group__require   必須
                = address_form.text_field :city, class: "address__main__form__content__group__input", placeholder:"例）横浜市緑区", id: "city"
              %div.address__main__form__content__group
                = f.label :street, "番地", class: "address__main__form__content__group__label" 
                %span.address__main__form__content__group__require   必須
                = address_form.text_field :street, class: "address__main__form__content__group__input", placeholder:"例）青山1-1-1", id: "street"
              %div.address__main__form__content__group
                = f.label :building_name, "建物名", class: "address__main__form__content__group__label" 
                %span.address__main__form__content__group__optional  任意
                = address_form.text_field :building_name, class: "address__main__form__content__group__input", placeholder:"例）柳ビル103", id: "building_name"
              %div.address__main__form__content__group
                = f.label :phone, "電話", class: "address__main__form__content__group__label" 
                %span.address__main__form__content__group__optional   任意
                = address_form.text_field :phone_optional, class: "address__main__form__content__group__input", placeholder:"例）09012345678", id: "phone_optional"
              = f.submit "次へ進む", class: "address__main__form__content__btn"
  = render 'layouts/second_footer'

app/views/signup/complete.html.haml
.complete
  %header.complete__header
    %h1.complete__header__left
      = link_to "/" , class: "complete__header__left__logo" do
        = image_tag "fmarket_logo_red.svg", class: "complete__header__left__logo__img"
    %nav.complete__header__progress-bar
      %ol.complete__header__progress-bar__clearfix
        %li.complete__header__progress-bar__text
          会員情報
          .complete__header__progress-bar__status.active
        %li.complete__header__progress-bar__text
          電話番号認証
          .complete__header__progress-bar__status.active
        %li.complete__header__progress-bar__text
          お届け先住所入力
          .complete__header__progress-bar__status.active
        %li.complete__header__progress-bar__text
          支払い方法
          .complete__header__progress-bar__status.active
        %li.complete__header__progress-bar__text.active
          完了
          .complete__header__progress-bar__status.active.last
  %main.complete__main
    %section.complete__main__container
      %h2.complete__main__container__head  会員登録完了
      %form.complete__main__form
        %div.complete__main__form__content
          %div.complete__main__form__content__group
          %h2.complete__main__form__content__message 
            ありがとうございます。
            %br
            会員登録が完了しました。
          = link_to "フリマをはじめる", products_path, class: "complete__main__form__content__btn"
      %complete__footer
        .complete__footer-upper
          .complete__footer-upper__banner
            = image_tag "bg_complete_footer.jpg"
            .complete__footer-upper__banner--title
              ＼ スマホでかんたんフリマアプリ ／
            .complete__footer-upper__banner--text
              今すぐ無料ダウンロード！
            .complete__footer-upper__banner--app
              = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?206587138", size: "135x40")
            .complete__footer-upper__banner--google
              = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?206587138", size: "135x40")
            .complete__footer-upper__banner--smartphone
              = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?206587138", height: "261px", width: "300"
  = render 'layouts/second_footer'

app/views/signup/pay_way.html.haml
.pay_way
  %header.pay_way__header
    %h1.pay_way__header__left
      = link_to "/" , class: "pay_way__header__left__logo" do
        = image_tag "fmarket_logo_red.svg", class: "pay_way__header__left__logo__img"
    %nav.pay_way__header__progress-bar
      %ol.pay_way__header__progress-bar__clearfix
        %li.pay_way__header__progress-bar__text
          会員情報
          .pay_way__header__progress-bar__status.active
        %li.pay_way__header__progress-bar__text
          電話番号認証
          .pay_way__header__progress-bar__status.active
        %li.pay_way__header__progress-bar__text
          お届け先住所入力
          .pay_way__header__progress-bar__status.active
        %li.pay_way__header__progress-bar__text.active
          支払い方法
          .pay_way__header__progress-bar__status.active.last
        %li.pay_way__header__progress-bar__text
          完了
          .pay_way__header__progress-bar__status
  %main.pay_way__main
    %section.pay_way__main__container
      %h2.pay_way__main__container__head  支払い方法
      = form_tag(signup_index_path, method: :post, id:"charge-form", name: "inputForm", class: "pay_way__main__form") do
        %div.pay_way__main__form__content
          %div.pay_way__main__form__content__group
            %label.pay_way__main__form__content__group__label  カード番号
            %span.pay_way__main__form__content__group__require   必須
            = text_field_tag "number", "", class: "number pay_way__main__form__content__group__input", placeholder:"半角数字のみ", id: "card_number", name: "card_number"
            %ul.pay_way__main__form__content__group__card-list
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "visa.svg", class: "pay_way__main__form__content__group__card-list__img__visa"
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "master-card.svg", class: "pay_way__main__form__content__group__card-list__img__master"
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "saison-card.svg", class: "pay_way__main__form__content__group__card-list__img__saison"
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "jcb.svg", class: "pay_way__main__form__content__group__card-list__img__jcb"
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "american_express.svg", class: "pay_way__main__form__content__group__card-list__img__amex"
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "dinersclub.svg", class: "pay_way__main__form__content__group__card-list__img__dinersclub"
              %li.pay_way__main__form__content__group__card-list__img
                = image_tag "discover.svg", class: "pay_way__main__form__content__group__card-list__img__discover"
            #card_number_error
          %div.pay_way__main__form__content__group
            %label.pay_way__main__form__content__group__label  有効期限
            %span.pay_way__main__form__content__group__require   必須
            .pay_way__main__form__content__group__expire
              .pay_way__main__form__content__group__expire__select
                %i.fas.fa-chevron-down.fa-lg.pay_way__main__form__content__group__expire__select__icon
                %select#exp_month{name: "exp_month", type: "text", class: "pay_way__main__form__content__group__expire__select__pulldown", name: "exp_month" }
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
              %span.pay_way__main__form__content__group__expire__select__text  月
            .pay_way__main__form__content__group__expire
              .pay_way__main__form__content__group__expire__select
                %i.fas.fa-chevron-down.fa-lg.pay_way__main__form__content__group__expire__select__icon
                %select#exp_year{name: "exp_year", type: "text", class:"pay_way__main__form__content__group__expire__select__pulldown", name: "exp_year" }
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
              %span.pay_way__main__form__content__group__expire__select__text  年
            #exp_date_error
          %div.pay_way__main__form__content__group
            %label.pay_way__main__form__content__group__label  セキュリティコード
            %span.pay_way__main__form__content__group__require   必須
            = text_field_tag "cvc", "", id: "cvc", class: "pay_way__main__form__content__group__input", placeholder:"カード背面4桁もしくは3桁の番号", name: "cvc"
          .pay_way__main__form__content__text-right
            .pay_way__main__form__content__text-right__text 
              %span.pay_way__main__form__content__text-right__icon ?
              カード裏面の番号とは？
          #card_token
          = submit_tag "次へ進む", class: "pay_way__main__form__content__btn", id: "token_submit"
  = render 'layouts/second_footer'

app/views/signup/phone.html.haml
.phone
  %header.phone__header
    %h1.phone__header__left
      = link_to "/" , class: "phone__header__left__logo" do
        = image_tag "fmarket_logo_red.svg", class: "phone__header__left__logo__img"
    %nav.phone__header__progress-bar
      %ol.phone__header__progress-bar__clearfix
        %li.phone__header__progress-bar__text
          会員情報
          .phone__header__progress-bar__status.active
        %li.phone__header__progress-bar__text.active
          電話番号認証
          .phone__header__progress-bar__status.active.last
        %li.phone__header__progress-bar__text
          お届け先住所入力
          .phone__header__progress-bar__status
        %li.phone__header__progress-bar__text
          支払い方法
          .phone__header__progress-bar__status
        %li.phone__header__progress-bar__text
          完了
          .phone__header__progress-bar__status
  %main.phone__main
    %section.phone__main__container
      %h2.phone__main__container__head  電話番号の確認
      = form_for(@user, url: address_signup_index_path, method: :get, html: {class: "phone__main__form", id: "signup-form"}) do |f|
        %div.phone__main__form__content
          = render partial: 'layouts/error-messages', locals: { user: @user, column: "phone"}
          %div.phone__main__form__content__group
            %label.phone__main__form__content__group__label
            = f.label :phone, "携帯電話の番号", class: "phone__main__form__content__group__label"
            = f.text_field :phone, class: "phone__main__form__content__group__input", placeholder:"携帯電話の番号を入力", id: "phone"
          #phone_error
          %p.phone__main__form__content__group__phone-description
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = f.submit "SMSを送信する", class: "phone__main__form__content__btn"
          %p.phone__main__form__content__group__phone-description
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません
          .phone__main__form__content__text-right
            %p
              = link_to  "電話番号の確認が必要な理由", "", class: "phone__main__form__content__text-right__text"
              %i.fas.fa-chevron-right.phone__main__form__content__text-right__icon
  = render 'layouts/second_footer'

app/views/signup/registration.html.haml
.registration
  %header.registration__header
    %h1.registration__header__left
      = link_to "/" , class: "registration__header__left__logo" do
        = image_tag "fmarket_logo_red.svg", class: "registration__header__left__logo__img"
    %nav.registration__header__progress-bar
      %ol.registration__header__progress-bar__clearfix
        %li.registration__header__progress-bar__text.active
          会員情報
          .registration__header__progress-bar__status.active
        %li.registration__header__progress-bar__text
          電話番号認証
          .registration__header__progress-bar__status
        %li.registration__header__progress-bar__text
          お届け先住所入力
          .registration__header__progress-bar__status
        %li.registration__header__progress-bar__text
          支払い方法
          .registration__header__progress-bar__status
        %li.registration__header__progress-bar__text
          完了
          .registration__header__progress-bar__status
  %main.registration__main
    %section.registration__main__container
      %h2.registration__main__container__head  会員情報入力
      = form_for(@user, url: phone_signup_index_path, method: :get, html: {class: "registration__main__form", id: "signup-form"}) do |f|
        %div.registration__main__form__content
          = render partial: 'layouts/error-messages', locals: { user: @user, column: "email"}
          %div.registration__main__form__content__group
            = f.label :name, "ニックネーム", class: "registration__main__form__content__group__label" 
            %span.registration__main__form__content__group__require 必須
            - if session[:name] && session[:sns_existed_flag] == "yes"
              = f.text_field :name, class: "registration__main__form__content__group__input", placeholder:"例）フリマ太郎", id: "name", value: "#{session[:name]}"
            - else
              = f.text_field :name, class: "registration__main__form__content__group__input", placeholder:"例）フリマ太郎", id: "name"
          %div.registration__main__form__content__group
            = f.label :email, "メールアドレス", class: "registration__main__form__content__group__label"
            %span.registration__main__form__content__group__require   必須
            - if session[:email] && session[:sns_existed_flag] == "yes"
              = f.email_field :email, class:"registration__main__form__content__group__input", placeholder:"PC・携帯どちらでも可", id: "email", value: "#{session[:email]}"
            - else
              = f.email_field :email, class:"registration__main__form__content__group__input", placeholder:"PC・携帯どちらでも可", id: "email"
          - if session[:sns_existed_flag] == "yes"
            %div.registration__main__form__content__group{style: "display: none;"}
              = f.label :password, "パスワード", class: "registration__main__form__content__group__label"
              %span.registration__main__form__content__group__require  必須
              = f.password_field :password, class:"registration__main__form__content__group__input", placeholder:"7文字以上の半角英数字", id: "password", value: "#{session[:password]}"
              %p.registration__main__form__content__group__input__info  ※ 英字と数字の両方を含めて設定してください。
            %div.registration__main__form__content__group{style: "display: none;"}
              = f.label :password_confirmation, "パスワード(確認)", class: "registration__main__form__content__group__label"
              %span.registration__main__form__content__group__require  必須
              = f.password_field :password_confirmation, class:"registration__main__form__content__group__input", placeholder:"7文字以上の半角英数字", id: "password_confirmation", value: "#{session[:password]}"
          - else
            %div.registration__main__form__content__group
              = f.label :password, "パスワード", class: "registration__main__form__content__group__label"
              %span.registration__main__form__content__group__require  必須
              = f.password_field :password, class:"registration__main__form__content__group__input", placeholder:"7文字以上の半角英数字", id: "password"
              %p.registration__main__form__content__group__input__info  ※ 英字と数字の両方を含めて設定してください。
            %div.registration__main__form__content__group
              = f.label :password_confirmation, "パスワード(確認)", class: "registration__main__form__content__group__label"
              %span.registration__main__form__content__group__require  必須
              = f.password_field :password_confirmation, class:"registration__main__form__content__group__input", placeholder:"7文字以上の半角英数字", id: "password_confirmation"
          %div.registration__main__form__content__group
            %h3.registration__main__form__content__group__identification__head  本人確認
            %p.registration__main__form__content__group__identification__description
              安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          %div.registration__main__form__content__group
            %div
              = f.label :fullname, "お名前(全角)", class: "registration__main__form__content__group__label"
              %span.registration__main__form__content__group__require  必須
            = f.text_field :lastname, class: "registration__main__form__content__group__input__harf", placeholder:"例）山田", id: "lastname"
            = f.text_field :firstname, class: "registration__main__form__content__group__input__harf", placeholder:"例）彩", id: "firstname"
            #name_error
          %div.registration__main__form__content__group
            %div
              = f.label :fullname, "お名前(カナ)", class: "registration__main__form__content__group__label"
              %span.registration__main__form__content__group__require  必須
            = f.text_field :lastname_kana, class: "registration__main__form__content__group__input__harf", placeholder:"例）ヤマダ", id: "lastname_kana"
            = f.text_field :firstname_kana, class: "registration__main__form__content__group__input__harf", placeholder:"例）アヤ", id: "firstname_kana"
            #name_kana_error
          %div.registration__main__form__content__group
            = f.label :birthday, "生年月日", class: "registration__main__form__content__group__label"
            %span.registration__main__form__content__group__require  必須
            .registration__main__form__content__group__birthday
              .registration__main__form__content__group__birthday__select
                %i.fas.fa-chevron-down.fa-lg.registration__main__form__content__group__birthday__select__icon
                = f.select :birth_year, @user.set_4digit_year, {}, {class: "registration__main__form__content__group__birthday__select__pulldown", id: "birth_year"}
              %span.registration__main__form__content__group__birthday__select__text  年
              .registration__main__form__content__group__birthday__select
                %i.fas.fa-chevron-down.fa-lg.registration__main__form__content__group__birthday__select__icon
                = f.select :birth_month, @user.set_birth_month, {}, {class: "registration__main__form__content__group__birthday__select__pulldown", id: "birth_month"}
              %span.registration__main__form__content__group__birthday__select__text  月
              .registration__main__form__content__group__birthday__select
                %i.fas.fa-chevron-down.fa-lg.registration__main__form__content__group__birthday__select__icon
                = f.select :birth_day, @user.set_birth_day, {}, {class: "registration__main__form__content__group__birthday__select__pulldown", id: "birth_day"}
              %span.registration__main__form__content__group__birthday__select__text  日
              #birth_date_error
              .clearfix
              %p.registration__main__form__content__notice  ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        %div.registration__main__form__content
          .registration__main__form__content__btn-text
            %p.registration__main__form__content__btn-text「次へ進む」のボタンを押すことにより、
            = link_to "利用規約", "", class: "registration__main__form__content__btn-text__link"
            に
            %br
            %p.registration__main__form__content__btn-text__second 同意したものとみなします
          = f.submit "次へ進む", class: "registration__main__form__content__btn"
          .registration__main__form__content__text-right
            %p
              = link_to  "本人情報の登録について", "", class: "registration__main__form__content__text-right__text"
              %i.fas.fa-chevron-right.registration__main__form__content__text-right__icon
          .registration__main__form__content__recaptcha_term
            %p.registration__main__form__content__recaptcha_term__text
              This site is protected by reCAPTCHA and the Google
              = link_to "Privacy Policy", "", class: "registration__main__form__content__recaptcha_term__link"
              and
              = link_to "Terms of Service", "", class: "registration__main__form__content__recaptcha_term__link"
              apply.
  = render 'layouts/second_footer'