config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'products#index'
  resources :signup do
    collection do
      get 'registration'
      get 'phone'
      get 'address'
      get 'pay_way'
      get 'complete'
    end
  end

  resources :purchase,  only: [:show] do
    member do
      patch 'pay'
    end
    collection do
      get 'complete'
    end
  end

  resources :mypage do
    member do
      get 'exhibiting'
      get 'sold'
      get 'purchased'
      get 'profile'
      get 'card'
      get 'identification'
      get 'logout'
    end
  end

  resources :users, only: [:update]

  resources :products do
    member do
      patch 'release'
      patch 'suspension'
    end
    collection do
      get 'category_child', defaults: { format: 'json' }
      get 'category_grandchild', defaults: { format: 'json' }
      get 'size', defaults: { format: 'json' }
      get 'brand', defaults: { format: 'json' }
      get 'delivery_way'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      get 'delete'
    end
  end

  resources :purchase do
    collection do
      get 'purchase_confirmation'
    end
    member do
      get 'pay'
    end
  end

  resources :category do
    collection do
      get 'new', defaults: { format: 'json' }
    end
  end
  
  resources :searches, only: [:index] do
    collection do
      get 'detail_search'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  include SetCard
  before_action :set_card, only: [:new, :delete, :show]
  before_action :apply_gon
  before_action :set_parents

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def new # マイページでのカード情報入力
    gon.payjp_key = ENV["PAYJP_KEY"]
    redirect_to action: "show" if @card.present?
  end

  def create # マイページでのカード情報登録
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(current_user)
      else
        redirect_to action: "new"
      end
    end
  end

  def delete # マイページでのカード情報削除
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      redirect_to card_path(current_user)
    end
  end

  def show # マイページでのカード情報表示
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private
  def apply_gon
    gon.payjp_key = ENV["PAYJP_KEY"]
  end

end

app/views/card/new.html.haml
= render 'layouts/mypage_header'
- breadcrumb :card
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.card-registration-box
  %section.card-registration-box__container
    %h2.card-registration-box__container__head
      クレジットカード情報入力
    = form_tag(card_index_path, method: :post, id:"charge-form", name: "inputForm", class: "card-registration-box__form") do
      %div.card-registration-box__form__content
        %div.card-registration-box__form__content__group
          %label.card-registration-box__form__content__group__label  カード番号
          %span.card-registration-box__form__content__group__require   必須
          = text_field_tag "number", "", class: "number card-registration-box__form__content__group__input", placeholder:"半角数字のみ", id: "card_number", name: "card_number"
          %ul.card-registration-box__form__content__group__card-list
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "visa.svg", class: "card-registration-box__form__content__group__card-list__img__visa"
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "master-card.svg", class: "card-registration-box__form__content__group__card-list__img__master"
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "saison-card.svg", class: "card-registration-box__form__content__group__card-list__img__saison"
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "jcb.svg", class: "card-registration-box__form__content__group__card-list__img__jcb"
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "american_express.svg", class: "card-registration-box__form__content__group__card-list__img__amex"
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "dinersclub.svg", class: "card-registration-box__form__content__group__card-list__img__dinersclub"
            %li.card-registration-box__form__content__group__card-list__img
              = image_tag "discover.svg", class: "card-registration-box__form__content__group__card-list__img__discover"
          #card_number_error
        %div.card-registration-box__form__content__group
          %label.card-registration-box__form__content__group__label  有効期限
          %span.card-registration-box__form__content__group__require   必須
          .card-registration-box__form__content__group__expire
            .card-registration-box__form__content__group__expire__select
              %i.fas.fa-chevron-down.fa-lg.card-registration-box__form__content__group__expire__select__icon
              %select#exp_month{name: "exp_month", type: "text", class: "card-registration-box__form__content__group__expire__select__pulldown", name: "exp_month" }
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
            %span.card-registration-box__form__content__group__expire__select__text  月
            .card-registration-box__form__content__group__expire__select
              %i.fas.fa-chevron-down.fa-lg.card-registration-box__form__content__group__expire__select__icon
              %select#exp_year{name: "exp_year", type: "text", class:"card-registration-box__form__content__group__expire__select__pulldown", name: "exp_year" }
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
            %span.card-registration-box__form__content__group__expire__select__text  年
          #exp_date_error
        %div.card-registration-box__form__content__group
          %label.card-registration-box__form__content__group__label  セキュリティコード
          %span.card-registration-box__form__content__group__require   必須
          = text_field_tag "cvc", "", id: "cvc", class: "card-registration-box__form__content__group__input", placeholder:"カード背面4桁もしくは3桁の番号", name: "cvc"
        .card-registration-box__form__content__text-right
          .card-registration-box__form__content__text-right__text 
            %span.card-registration-box__form__content__text-right__icon ?
            カード裏面の番号とは？
          #card_token
          = submit_tag "追加する", class: "card-registration-box__form__content__btn", id: "token_submit"
= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/card/show.html.haml
= render 'layouts/mypage_header'
- breadcrumb :card
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.card-box
  %section.card-box__container
    %h2.card-box__container__head
      支払い方法
    .card-box__container__inner
      %section
        .card-box__container__inner__content
          %h3.card-box__container__inner__content__head
            クレジットカード一覧
      - if @default_card_information.present?
        %ul
          %li.card-box__container__inner__content__card-list
            = form_tag(delete_card_index_path, method: :get, id:"charge-form", name: "inputForm", class: "card-box__container__inner__content__card-list__wrapper") do
              %figure.card-box__container__inner__content__card-list__img
                = image_tag "visa.svg", class: "card-box__container__inner__content__card-list__img__visa"
              %div.card-box__container__inner__content__card-list__card-number
                = "**** **** **** " + @default_card_information.last4
              %div.card-box__container__inner__content__card-list__exp_date
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
              = submit_tag "削除する", class: "card-box__container__inner__content__card-list__btn", id: "token_submit"
      - if @default_card_information.nil?
        %section.card-box__container__inner__addition
          .card-box__container__inner__addition__content
            = link_to new_card_path, class: "card-box__container__inner__addition__content__btn" do
              %i.far.fa-credit-card.fa-lg.card-box__container__inner__addition__content__btn__icon
              クレジットカードを追加する
      .card-box__container__inner__text-right
        %p
          = link_to  "支払い方法について", "", class: "phone__main__form__content__text-right__text"
          %i.fas.fa-chevron-right.card-box__container__inner__text-right__icon
= render 'layouts/footer'
= render 'layouts/exhibit-btn'