config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'products#index'
  resources :signup do
    collection do
      get 'registration'
      get 'phone'
      get 'address'
      get 'pay_way'
      get 'complete'
    end
  end

  resources :purchase,  only: [:show] do
    member do
      patch 'pay'
    end
    collection do
      get 'complete'
    end
  end

  resources :mypage do
    member do
      get 'exhibiting'
      get 'sold'
      get 'purchased'
      get 'profile'
      get 'card'
      get 'identification'
      get 'logout'
    end
  end

  resources :users, only: [:update]

  resources :products do
    member do
      patch 'release'
      patch 'suspension'
    end
    collection do
      get 'category_child', defaults: { format: 'json' }
      get 'category_grandchild', defaults: { format: 'json' }
      get 'size', defaults: { format: 'json' }
      get 'brand', defaults: { format: 'json' }
      get 'delivery_way'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      get 'delete'
    end
  end

  resources :purchase do
    collection do
      get 'purchase_confirmation'
    end
    member do
      get 'pay'
    end
  end

  resources :category do
    collection do
      get 'new', defaults: { format: 'json' }
    end
  end
  
  resources :searches, only: [:index] do
    collection do
      get 'detail_search'
    end
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :apply_gon
  before_action :set_user, only: [:exhibiting, :sold, :purchased, :profile]
  before_action :set_parents

  def show # マイページ
  end

  def exhibiting # 出品した商品 - 出品中
    @product = @user.products.where.not(transaction_status: 1).page(params[:page]).per(12).order("created_at DESC")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def sold #出品した商品 - 売却済み
    @product = @user.products.where(transaction_status: 1).page(params[:page]).per(12).order("created_at DESC")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def purchased #購入した商品 - 過去の取引
    @product = Product.all.where(buyer_id: current_user.id).page(params[:page]).per(12).order("created_at DESC")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def card # 支払い方法
  end

  def identification # 本人確認
  end

  def profile # プロフィール
  end

  def logout # ログアウト
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def apply_gon
    gon.payjp_key = ENV["PAYJP_KEY"]
  end
end

app/views/mypage/_exhibiting_products.html.haml
- @product.each do |product|
  = link_to product_path(product) do
    .exhibiting__product
      .exhibiting__product--img
        = image_tag product.images.first.image, size: "50x50"
        .exhibiting__product--name
          = product.name
          - if product.transaction_status == 0
            .exhibiting__product--selling
              出品中
          - elsif product.transaction_status == 2
            .exhibiting__product--suspension
              公開停止中
          - elsif product.transaction_status == 1 && product.buyer_id == current_user.id
            .exhibiting__product--purchased
              取引完了
          - elsif product.transaction_status == 1
            .exhibiting__product--sold
              売却済
      .exhibiting__product--detail
        %i.fas.fa-chevron-right
= paginate(@product, remote: true)

app/views/mypage/exhibiting.html.haml
= render 'layouts/mypage_header'
- breadcrumb :exhibiting
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.exhibiting
  .exhibiting__header
    出品した商品
  .exhibiting__status
    = link_to exhibiting_mypage_path(current_user), class: "exhibiting__status--current" do
      出品中
    .exhibiting__status--other
      取引中
    = link_to sold_mypage_path(current_user), class: "exhibiting__status--other" do
      売却済み
  - unless @product.any?
    .exhibiting__none
      .exhibiting__none--icon
        = image_tag "logo_white.svg", size: "85x85"
      .exhibiting__none--text
        出品中の商品がありません
  - else
    #user_products
      = render 'exhibiting_products'

= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/exhibiting.js.haml
$("#user_products").html("#{j(render partial: 'exhibiting_products')}");

app/views/mypage/identification.html.haml
= render 'layouts/mypage_header'
- breadcrumb :personal
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.identification-box
  %section.identification-box__container
    %h2.identification-box__container__head
      本人情報の登録
    %form.identification-box__form
      .identification-box__form__header
        %p.identification-box__form__header--text
          お客様の本人情報をご登録下さい。
          %br
          登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.identification-box__form__header--link
          = link_to "https://www.mercari.com/jp/help_center/article/495/", class: "identification-box__form__header--link--tag" do
            本人確認書類のアップロードについて
          %i.fas.fa-chevron-right.identification-box__form__header--link--icon
      .identification-box__form__group
        %label.identification-box__form__group--label
          お名前
        %p.identification-box__form__group--text
          = current_user.lastname + " " + current_user.firstname
      .identification-box__form__group
        %label.identification-box__form__group--label
          お名前カナ
        %p.identification-box__form__group--text
          = current_user.lastname_kana + " " + current_user.firstname_kana
      .identification-box__form__group
        %label.identification-box__form__group--label
          生年月日
        %p.identification-box__form__group--text
          = current_user.birth_year.to_s + "/" + current_user.birth_month.to_s + "/" + current_user.birth_day.to_s
      .identification-box__form__group-pulldown
        %label
          郵便番号
        %span.identification-box__form--form-arbitrary
          任意
        %br
        %input.identification-box__form__input-form{placeholder: "例）1234567", type: "text", value: ""}/
      .identification-box__form__group-pulldown
        %label
          都道府県
        %span.identification-box__form--form-arbitrary
          任意
        = form_for '' do |f|
          .identification-box__form__group-pulldown__select-wrap
            %i.fas.fa-chevron-down.fa-lg.identification-box__form__group-pulldown__select-wrap__icon
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--", class: 'containt__main__container__inner__sell-form__select-wrap__list'
        .identification-box__form__group-pulldown
          %label
            市区町村
          %span.identification-box__form--form-arbitrary
            任意
          %br
          %input.identification-box__form__input-form{placeholder: "例）横浜市緑区", type: "text", value: ""}/
        .identification-box__form__group-pulldown
          %label
            番地
          %span.identification-box__form--form-arbitrary
            任意
          %br
          %input.identification-box__form__input-form{placeholder: "例）青山1-1-1", type: "text", value: ""}/
        .identification-box__form__group-pulldown
          %label
            建物名
          %span.identification-box__form--form-arbitrary
            任意
          %br
          %input.identification-box__form__input-form{placeholder: "例）柳ビル103", type: "text", value: ""}/
          %button.identification-box__form__btn-red{type: "submit"}
            登録する
          .identification-box__form__bottom
            = link_to "https://www.mercari.com/jp/help_center/article/423/", class: "identification-box__form__header--link--tag" do
              本人情報の登録について
            %i.fas.fa-chevron-right.identification-box__form__header--link--icon
= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/logout.html.haml
= render 'layouts/mypage_header'
- breadcrumb :logout
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
= render 'layouts/logout-btn'
= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/profile.html.haml
= render 'layouts/mypage_header'
- breadcrumb :profile
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
= form_for(@user, url: user_path(current_user), method: :put, html: {class: "profile-box"}) do |f|
  %h2.profile-box__head
    プロフィール
  = image_tag "bg_mypage.jpg", class: "profile-box__top"
  .profile-box__top__icon
    = image_tag "user_noimage.png", class: "profile-box__top__icon--image", size: "60x60"
    = f.text_field :name, class: "profile-box__top__icon--input", placeholder: "例)AYA☆セール中", id: "name"
  .profile-box__containt
    = f.text_area :introduction, class: "profile-box__containt__textarea", placeholder:"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", id: "introduction"
    = f.submit "変更する", class: "profile-box__containt__register"
= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/purchased.html.haml
= render 'layouts/mypage_header'
- breadcrumb :purchased
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.purchased
  .purchased__header
    購入した商品
  .purchased__status
    .purchased__status--other
      取引中
    = link_to purchased_mypage_path(current_user), class: "purchased__status--current" do
      過去の取引
  - unless @product.any?
    .purchased__none
      .purchased__none--icon
        = image_tag "logo_white.svg", size: "85x85"
      .purchased__none--text
        過去に取引した商品がありません
  - else
    #user_products
      = render 'exhibiting_products'

= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/purchased.js.haml
$("#user_products").html("#{j(render partial: 'exhibiting_products')}");

app/views/mypage/show.html.haml
= render 'layouts/mypage_header'
- breadcrumb :mypage
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.mypage-box
  %section.mypage-box__head
    = link_to "" "", class: "mypage-box__head__link" do
      %figure.mypage-box__head__link__avator
        = image_tag "user_noimage.png", class: "mypage-box__head__link__avator__img", size: "60x60"
      %h2.mypage-box__head__link__nickname
        = current_user.name
      .mypage-box__head__link__numbers
        .mypage-box__head__link__numbers__name 
          評価
          %span.mypage-box__head__link__numbers__num
            3
        .mypage-box__head__link__numbers__name
          出品数
          %span.mypage-box__head__link__numbers__num
            4
  %section.mypage-box__upper
    %ul.mypage-box__upper__tabs
      %li.mypage-box__upper__tabs__tab.active
        %h3.mypage-box__upper__tabs__tab__name
          = link_to "お知らせ", "", class: "mypage-box__upper__tabs__tab__name__link"
      %li.mypage-box__upper__tabs__tab
        %h3.mypage-box__upper__tabs__tab__name
          = link_to "やることリスト", "", class: "mypage-box__upper__tabs__tab__name__link"
    .mypage-box__upper__content
      %ul.mypage-box__upper__content
        %li.mypage-box__upper__content__item
          = link_to root_path, class: "mypage-box__upper__content__item__link" do
            .mypage-box__upper__content__item__link__logo
              = image_tag "logo_white.svg", class: "mypage-box__upper__content__item__link__logo__img", size: "48x48"
            .mypage-box__upper__content__item__link__body
              .mypage-box__upper__content__item__link__body__text
                《今から3日間限定》参加ボタン押すだけでP1,000もらえるチャンス！
              %time.mypage-box__upper__content__item__link__body__time
                %i.far.fa-clock.mypage-box__upper__content__item__link__body__time__icon
                %span.mypage-box__upper__content__item__link__body__time__text
                  46分前
            %i.fas.fa-chevron-right.mypage-box__upper__content__item__link__body__icon
        %li.mypage-box__upper__content__item
          = link_to root_path, class: "mypage-box__upper__content__item__link" do
            .mypage-box__upper__content__item__link__logo
              = image_tag "logo_white.svg", class: "mypage-box__upper__content__item__link__logo__img", size: "48x48"
            .mypage-box__upper__content__item__link__body
              .mypage-box__upper__content__item__link__body__text
                事務局からの個別メッセージ「ログイン通知」
              %time.mypage-box__upper__content__item__link__body__time
                %i.far.fa-clock.mypage-box__upper__content__item__link__body__time__icon
                %span.mypage-box__upper__content__item__link__body__time__text
                  1日前
            %i.fas.fa-chevron-right.mypage-box__upper__content__item__link__body__icon
        %li.mypage-box__upper__content__item
          = link_to root_path, class: "mypage-box__upper__content__item__link" do
            .mypage-box__upper__content__item__link__logo
              = image_tag "logo_white.svg", class: "mypage-box__upper__content__item__link__logo__img", size: "48x48"
            .mypage-box__upper__content__item__link__body
              .mypage-box__upper__content__item__link__body__text
                事務局からの個別メッセージ「ログイン通知」
              %time.mypage-box__upper__content__item__link__body__time
                %i.far.fa-clock.mypage-box__upper__content__item__link__body__time__icon
                %span.mypage-box__upper__content__item__link__body__time__text
                  1日前
            %i.fas.fa-chevron-right.mypage-box__upper__content__item__link__body__icon
        %li.mypage-box__upper__content__item
          = link_to root_path, class: "mypage-box__upper__content__item__link" do
            .mypage-box__upper__content__item__link__logo
              = image_tag "logo_white.svg", class: "mypage-box__upper__content__item__link__logo__img", size: "48x48"
            .mypage-box__upper__content__item__link__body
              .mypage-box__upper__content__item__link__body__text
                《P2,000かならずもらえる》メルペイスマート払いを設定して決済するだけ！買うものは何でもOK
              %time.mypage-box__upper__content__item__link__body__time
                %i.far.fa-clock.mypage-box__upper__content__item__link__body__time__icon
                %span.mypage-box__upper__content__item__link__body__time__text
                  2日前
            %i.fas.fa-chevron-right.mypage-box__upper__content__item__link__body__icon
        %li.mypage-box__upper__content__item
          = link_to root_path, class: "mypage-box__upper__content__item__link" do
            .mypage-box__upper__content__item__link__logo
              = image_tag "logo_white.svg", class: "mypage-box__upper__content__item__link__logo__img", size: "48x48"
            .mypage-box__upper__content__item__link__body
              .mypage-box__upper__content__item__link__body__text
                事務局からの個別メッセージ「ログイン通知」
              %time.mypage-box__upper__content__item__link__body__time
                %i.far.fa-clock.mypage-box__upper__content__item__link__body__time__icon
                %span.mypage-box__upper__content__item__link__body__time__text
                  2日前
            %i.fas.fa-chevron-right.mypage-box__upper__content__item__link__body__icon
        %li.mypage-box__upper__content__item__link
          = link_to "一覧を見る", root_path, class: "mypage-box__upper__content__item__link__btn"
  %section.mypage-box__products
    %h2.mypage-box__products__head
      購入した商品
    %ul.mypage-box__products__tabs
      %li.mypage-box__products__tabs__tab.active
        %h3.mypage-box__products__tabs__tab__name
          = link_to "取引中", "", class: "mypage-box__products__tabs__tab__name__link"
      %li.mypage-box__products__tabs__tab
        %h3.mypage-box__products__tabs__tab__name
          = link_to "過去の取引", "", class: "mypage-box__products__tabs__tab__name__link"
    .mypage-box__products__content
      %ul.mypage-box__products__content
        %li.mypage-box__products__content__item
          = link_to root_path, class: "mypage-box__products__content__item__link" do
            .mypage-box__products__content__item__link__logo
              = image_tag "product_sample.jpg", class: "mypage-box__products__content__item__link__logo__img"
            .mypage-box__products__content__item__link__body
              .mypage-box__products__content__item__link__body__text
                作りながら学ぶ HTML/CSSデザインの教科書
              .mypage-box__products__content__item__link__body__status.not-verified
                受取評価待ち
            %i.fas.fa-chevron-right.mypage-box__products__content__item__link__body__icon
        %li.mypage-box__products__content__item
          = link_to root_path, class: "mypage-box__products__content__item__link" do
            .mypage-box__products__content__item__link__logo
              = image_tag "product_sample.jpg", class: "mypage-box__products__content__item__link__logo__img"
            .mypage-box__products__content__item__link__body
              .mypage-box__products__content__item__link__body__text
                作りながら学ぶ HTML/CSSデザインの教科書
              .mypage-box__products__content__item__link__body__status.not-shipped
                発送待ち
            %i.fas.fa-chevron-right.mypage-box__products__content__item__link__body__icon
        %li.mypage-box__products__content__item
          = link_to root_path, class: "mypage-box__products__content__item__link" do
            .mypage-box__products__content__item__link__logo
              = image_tag "product_sample.jpg", class: "mypage-box__products__content__item__link__logo__img"
            .mypage-box__products__content__item__link__body
              .mypage-box__products__content__item__link__body__text
                作りながら学ぶ HTML/CSSデザインの教科書
              .mypage-box__products__content__item__link__body__status.not-shipped
                発送待ち
            %i.fas.fa-chevron-right.mypage-box__products__content__item__link__body__icon
= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/sold.html.haml
= render 'layouts/mypage_header'
- breadcrumb :sold
= render 'layouts/breadcrumbs'
= render 'layouts/sidebar'
.exhibiting
  .exhibiting__header
    出品した商品
  .exhibiting__status
    = link_to exhibiting_mypage_path(current_user), class: "exhibiting__status--other" do
      出品中
    .exhibiting__status--other
      取引中
    = link_to sold_mypage_path(current_user), class: "exhibiting__status--current" do
      売却済み
  - unless @product.any?
    .exhibiting__none
      .exhibiting__none--icon
        = image_tag "logo_white.svg", size: "85x85"
      .exhibiting__none--text
        売却済みの商品がありません
  - else
    #user_products
      = render 'exhibiting_products'

= render 'layouts/footer'
= render 'layouts/exhibit-btn'

app/views/mypage/sold.js.haml
$("#user_products").html("#{j(render partial: 'exhibiting_products')}");