config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'products#index'
  resources :signup do
    collection do
      get 'registration'
      get 'phone'
      get 'address'
      get 'pay_way'
      get 'complete'
    end
  end

  resources :purchase,  only: [:show] do
    member do
      patch 'pay'
    end
    collection do
      get 'complete'
    end
  end

  resources :mypage do
    member do
      get 'exhibiting'
      get 'sold'
      get 'purchased'
      get 'profile'
      get 'card'
      get 'identification'
      get 'logout'
    end
  end

  resources :users, only: [:update]

  resources :products do
    member do
      patch 'release'
      patch 'suspension'
    end
    collection do
      get 'category_child', defaults: { format: 'json' }
      get 'category_grandchild', defaults: { format: 'json' }
      get 'size', defaults: { format: 'json' }
      get 'brand', defaults: { format: 'json' }
      get 'delivery_way'
    end
  end

  resources :card, only: [:new, :show, :create] do
    collection do
      get 'delete'
    end
  end

  resources :purchase do
    collection do
      get 'purchase_confirmation'
    end
    member do
      get 'pay'
    end
  end

  resources :category do
    collection do
      get 'new', defaults: { format: 'json' }
    end
  end
  
  resources :searches, only: [:index] do
    collection do
      get 'detail_search'
    end
  end
end

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs pretext: "", separator: " &rsaquo; ", class: "breadcrumbs__list"

app/views/layouts/_breadcrumbs_product.haml
.breadcrumbs-product
  = breadcrumbs pretext: "", separator: " &rsaquo; ", class: "breadcrumbs-product__list"

app/views/layouts/_error-messages.html.haml
- if user.errors.any?
  - unless user.valid?
    - if errors = user.errors.full_messages_for(column.to_sym)
      - errors.each do |error|
        %p.validation_error
          = error

app/views/layouts/_exhibit-btn.html.haml
= link_to new_product_path, class: "exhibit" do
  .exhibit__btn 出品
  %i.fas.fa-camera{class: "exhibit__btn--icon"}

app/views/layouts/_footer.html.haml
%footer
  .footer-upper
    .footer-upper__banner
      = image_tag "fotter_bg.jpg" , height: "266", width: "1440"
      .footer-upper__banner--title
        スマホでかんたんフリマアプリ
      .footer-upper__banner--text
        今すぐ無料ダウンロード！
      .footer-upper__banner--logo
        = image_tag "fmarket_icon.png", width: "68"
      .footer-upper__banner--app
        = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?206587138", size: "135x40")
      .footer-upper__banner--google
        = link_to image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?206587138", size: "135x40")
      -# .footer-upper__banner--smartphone
      -#   = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?206587138", height: "261px", width: "300"
  .footer-lower
    .footer-contents-box
      .footer-contents-box__title
        フリマについて
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 会社概要（運営会社）
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 採用情報
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} プレスリリース
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 公式ブログ
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} フリマロゴ利用ガイドライン
      .footer-contents-box__icon
        = link_to "", class: "footer-contents-box__icon--twitter" do
          %i.fab.fa-twitter
        = link_to "", class: "footer-contents-box__icon--facebook" do
          %i.fab.fa-facebook-square
    .footer-contents-box
      .footer-contents-box__title
        ヘルプ＆ガイド
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} フリマガイド
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} らくらくフリマ便
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} ゆうゆうフリマ便
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 大型フリマ便
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 車体取引ガイド
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} フリマあんしん・あんぜん宣言！
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 偽ブランド品撲滅への取り組み
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} フリマボックス
    .footer-contents-box-privacy-left
      .footer-contents-box__title
        プライバシーと利用規約
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} プライバシーポリシー
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} フリマ利用規約
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} あんしんスマホサポート制度に関する利用特約
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} コンプライアンスポリシー
    .footer-contents-box-privacy-right
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} 個人データの安全管理に係る基本方針
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} 特定商取引に関する表記
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} 資金決済法に基づく表示
      .footer-contents-list-privacy
        = link_to "" do
          %span{class: "footer-contents-box__links"} 法令遵守と犯罪防止のために
    .footer-contents-box-country
      .footer-contents-box__title
        国
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} 日本
      .footer-contents-box__list
        = link_to "" do
          %span{class: "footer-contents-box__links"} United States
    .footer-copyright
      %small © 2019 Fmarket

app/views/layouts/_header.html.haml
.header-wrapper
  .header-upper-title
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg", size: "134x36"
  = form_tag(searches_path, method: :get) do
    = text_field_tag :search, "", placeholder: "何かお探しですか？", class: "search-box"
    %label
      %i.fas.fa-search{class: "search-icon"}
      = submit_tag 'search', name: nil, class: "search-btn"
  .header-lower-left
    .header-lower-left__category
      %div.category_btn
        %i.fas.fa-list-ul{class: "list-icon"}
        %span.parent_category
          カテゴリーから探す
      .category_box
        .parents_list
          - @parents.each do |parent|
            = link_to "#{parent.name}", category_path(parent) , class: "category-parent", id: "#{parent.id}"
        .category_list_children
        .grand_children_list
    .header-lower-left__brands
      %i.fas.fa-tags{class: "tags-icon"}
      %span ブランドから探す
  .header-lower-right
    = link_to new_user_registration_path, class: "header-lower-right__signup" do
      %span{class: "signup-btn"} 新規登録
    = link_to new_user_session_path, class: "header-lower-right__login" do
      %span{class: "login-btn"} ログイン

app/views/layouts/_logout-btn.html.haml
.logout-box
  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-box__btn"

app/views/layouts/_mypage_header.html.haml
.mypage-header-wrapper
  .header-upper-title
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg", size: "134x36"
  = form_tag(searches_path, method: :get) do
    = text_field_tag :search, "", placeholder: "何かお探しですか？", class: "search-box"
    %label
      %i.fas.fa-search{class: "search-icon"}
      = submit_tag 'search', name: nil, class: "search-btn"
  .header-lower-left
    .header-lower-left__category
      %div.category_btn
        %i.fas.fa-list-ul{class: "list-icon"}
        %span カテゴリーから探す
      .category_box
        .parents_list
          - @parents.each do |parent|
            = link_to "#{parent.name}", category_path(parent) , class: "category-parent", id: "#{parent.id}"
        .category_list_children
        .grand_children_list
    .header-lower-left__brands
      %i.fas.fa-tags{class: "tags-icon"}
      %span ブランドから探す
  .header-lower-right-mypage
    .header-lower-right-mypage__likes
      .header-lower-right-mypage__likes--icon
        %i.far.fa-heart
      .header-lower-right-mypage__likes--title
        いいね！一覧
    .header-lower-right-mypage__notice
      .header-lower-right-mypage__notice--icon
        %i.far.fa-bell
      .header-lower-right-mypage__notice--title
        お知らせ
    .header-lower-right-mypage__to-do-list
      .header-lower-right-mypage__to-do-list--icon
        %i.fas.fa-check
      .header-lower-right-mypage__to-do-list--title
        やることリスト
    .header-lower-right-mypage__user
      = link_to mypage_path(current_user) do
        = image_tag '//static.mercdn.net/images/member_photo_noimage_thumb.png', class: "header-lower-right-mypage__user--image", size: '32x32'
      = link_to "マイページ", mypage_path(current_user), class: "header-lower-right-mypage__user--title"
  .mypage-header-box
    .mypage-header-box__head
      %figure.mypage-header-box__head__bgimage
        %div.mypage-header-box__head__avatar
          = image_tag '//static.mercdn.net/images/member_photo_noimage_thumb.png', class: "mypage-header-box__head__avatar--img", size: '60x60'
        %figcaption.mypage-header-box__head__name
          = current_user.name
      %ul.mypage-header-box__head__review
        %li.mypage-header-box__head__review__text
          評価: 5
        %li.mypage-header-box__head__review__text
          出品数: 20
      .mypage-header-box__head__review__sales-point
        %div.mypage-header-box__head__review__sales-point__item
          %div.mypage-header-box__head__review__sales-point__item__left
            残高
          %div.mypage-header-box__head__review__sales-point__item__right
            ¥7,777
            %i.fas.fa-chevron-right.mypage-header-box__head__review__sales-point__item__icon
        %div.mypage-header-box__head__review__sales-point__item
          %div.mypage-header-box__head__review__sales-point__item__left
            ポイント
          %div.mypage-header-box__head__review__sales-point__item__right
            P777
            %i.fas.fa-chevron-right.mypage-header-box__head__review__sales-point__item__icon
    .mypage-header-box__list
      .mypage-header-box__list__item
        いいね！一覧
        .mypage-header-box__list__item--detail
          %i.fas.fa-chevron-right
      = link_to exhibiting_mypage_path(current_user), class: "mypage-header-box__list__item" do
        出品した商品 - 出品中
        .mypage-header-box__list__item--detail
          %i.fas.fa-chevron-right
      .mypage-header-box__list__item
        出品した商品 - 取引中
        .mypage-header-box__list__item--detail
          %i.fas.fa-chevron-right
      = link_to sold_mypage_path(current_user), class: "mypage-header-box__list__item" do
        出品した商品 - 売却済み
        .mypage-header-box__list__item--detail
          %i.fas.fa-chevron-right
      .mypage-header-box__list__item
        購入した商品 - 取引中
        .mypage-header-box__list__item--detail
          %i.fas.fa-chevron-right
      = link_to purchased_mypage_path(current_user), class: "mypage-header-box__list__item" do
        購入した商品 - 過去の取引
        .mypage-header-box__list__item--detail
          %i.fas.fa-chevron-right

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_second_footer.html.haml
%footer.second__footer
  %nav
    %ul.second__footer__clearfix
      %li.second__footer__link
        = link_to "プライバシーポリシー", "", class: "second__footer__link__text"
      %li.second__footer__link
        = link_to "フリマ利用規約", "", class: "second__footer__link__text"
      %li.second__footer__link
        = link_to "特定商取引に関する表記", "", class: "second__footer__link__text"
  = link_to root_path, class: "second__footer__logo" do
    = image_tag "logo_gray.svg", size: "80x65", class: "second__footer__logo__img"
  %p
    %small.second__footer__text  ©︎ 2019 Fmarket

app/views/layouts/_sidebar.html.haml
.mypage-wrapper
  .sidebar
    = link_to mypage_path(current_user), class: "sidebar__list mypage-default" do
      マイページ
      .sidebar__list--detail
        %i.fas.fa-chevron-right.sidebar__list--detail--icon
    .sidebar__list
      お知らせ
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      やることリスト
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      いいね！一覧
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to new_product_path, class: "sidebar__list" do
      出品する
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to exhibiting_mypage_path(current_user), class: "sidebar__list mypage-exhibiting" do
      出品した商品 - 出品中
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      出品した商品 - 取引中
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to sold_mypage_path(current_user), class: "sidebar__list mypage-sold" do
      出品した商品 - 売却済み
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      購入した商品 - 取引中
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to purchased_mypage_path(current_user), class: "sidebar__list mypage-purchased" do
      購入した商品 - 過去の取引
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      ニュース一覧
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      評価一覧
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      ガイド
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      お問い合わせ
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__title
      メルペイ
    .sidebar__list
      売上・振込申請
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      ポイント
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__title
      設定
    = link_to profile_mypage_path(current_user), class: "sidebar__list mypage-profile" do
      プロフィール
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      発送元・お届け先住所変更
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to card_path(current_user), class: "sidebar__list mypage-card" do
      支払い方法
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      メール/パスワード
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to identification_mypage_path(current_user), class: "sidebar__list mypage-identification" do
      本人情報
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    .sidebar__list
      電話番号の確認
      .sidebar__list--detail
        %i.fas.fa-chevron-right
    = link_to logout_mypage_path(current_user), class: "sidebar__list mypage-logout" do
      ログアウト
      .sidebar__list--detail
        %i.fas.fa-chevron-right

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample58aNight
    = include_gon
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %script{src: "http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = favicon_link_tag('favicon.ico')
  %body
    = render 'layouts/notifications'
    = yield